### ISSUE TITLE
issue at the end of installing sqlite3

### ISSUE THREAD

**Issue by Alleno** [rubyonwindowsguides/rubyonwindowsguides.github.com#8]
Dear Bosko,

Thanks for an excellent Ruby guide. I definitely am in over my head on these topics as I am new to programming, but I was able to follow your guide all the way to the very last (or maybe last two steps) on installing sqlite3 gem. I reached the end, but I didn't already have a file called C:/tools. Is this a typo in your guide? I created this c:/tools folder and added the libsqlite3-0.dll, but I got an error message after requiring 'sqlite3'

irb(main):001:0> require 'sqlite3'
LoadError: 126: The specified module could not be found.   - C:/Ruby21/lib/ruby/
gems/2.1.0/gems/sqlite3-1.3.10/lib/sqlite3/sqlite3_native.so
        from C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require
.rb:55:in `require'
        from C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require
.rb:55:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.10/lib/sqlite3.rb:6:
in `rescue in <top (required)>'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.10/lib/sqlite3.rb:2:
in `<top (required)>'
        from C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require
.rb:135:in `require'
        from C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require
.rb:135:in `rescue in require'
        from C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require
.rb:144:in `require'
        from (irb):1
        from C:/Ruby21/bin/irb:11:in `<main>'

Should i put the dll in a different folder?

Best wishes,

Allen Wang

**Comment by bosko** [comment]
Hi Allen. This directory was created during Pik installation (http://rubyonwindowsguides.github.io/book/ch02-03.html). Directory c:\tools must be in the path.

**Comment by Alleno** [comment]
Ok Thanks Bosko, it worked, I added c:/tools to the path.
